### ISSUE TITLE
How to insert an array of enum?

### ISSUE THREAD

**Issue by JRaspass** [CurtTilmes/raku-dbpg#14]
So [raku.land](https://raku.land) currently defines a license enum for dists:
```sql
-- https://spdx.org/licenses/
CREATE TYPE license AS ENUM (
    'AGPL-3.0-only', 'AGPL-3.0-or-later', 'Apache-2.0', ...
);

CREATE TABLE dists (
    license license,
    ...
);
```

I'm trying to make this an array (`license license[]`) for the few dists that are licensed under multiple licenses but I'm having trouble writing an insert that both DB::Pg and PostgreSQL like, I've various combinations of:

```perl6
$sth.execute: ['AGPL-3.0-only', 'Apache-2.0'];
```
```sql
INSERT INTO dists (license) VALUES ($1)
```
```sql
INSERT INTO dists (license) VALUES ($1::text[])
```
```sql
INSERT INTO dists (license) VALUES ($1::license[])
```
But nothing works.

As a side note is there anything like `%ENV{DBI_TRACE}` from Perl to see what SQL is being executed by DB::Pg? I couldn't see it mentioned on the README.

**Comment by CurtTilmes** [comment]
The Raku side doesn't understand the enum type -- you can either write a new converter for the new type, or, since your type is based on strings anyway, just have PostgreSQL do the conversion for you.  Tell Raku the type is text by telling PostgreSQL to expect a text type in the field, but they also tell PostgreSQL to convert it to your new `license` type before using it.  Much easier to do than to explain..

```
insert into dists (license) values ($1::text[]::license[]
```

So Raku knows to send an array of text strings, but they get converted to an array of license types on PostgreSQL.

Cool, huh?

I don't have a trace field from Perl, but you can tell your postgres server to log queries by setting `log_statement` to `all` (or the type of statements you want to see). [logging](https://www.postgresql.org/docs/current/runtime-config-logging.html).

**Comment by JRaspass** [comment]
Ah I didn't think to try and coerce it twice, that works perfectly, thanks!
